### ISSUE TITLE
dxgi.dll is the issue(or not)

### ISSUE THREAD

**Issue by omeassanee** [ibldzn/yakuza-0-legend-style-fix#13]
I have the dxgi.dll for reshade but it work normally but when i replace the dxgi.dll from legend style fix it wont let me open the game

**Comment by ibldzn** [comment]
try using the asi version

**Comment by omeassanee** [comment]
sorry for asking but what do you mean by that?

**Comment by ibldzn** [comment]
https://github.com/ibldzn/yakuza-0-legend-style-fix#im-having-issue-with-your-mod-what-should-i-do
