### ISSUE TITLE
my game doesnt load mods now

### ISSUE THREAD

**Issue by Jack409I** [ibldzn/yakuza-0-legend-style-fix#14]
since im using a reshade i decided to use Y0LSF.asi to play instead, i also installed the asi loader to well, load it, and now when i try to use any mod with rmm it doesnt load it, is there any fix for this?

**Comment by ibldzn** [comment]
how does your game root directory look?

**Comment by Jack409I** [comment]
Hi, apparently it was my mistake because i downloaded the wrong asi loader, so yeah sorry for that
