### ISSUE TITLE
i opened the Y0LSF file using notepad to open it and it isnt working

### ISSUE THREAD

**Issue by LioTheBadAss** [ibldzn/yakuza-0-legend-style-fix#16]
hello. i have installed your yakuza 0 legend style fix mod and i need some help. when i opened the file i accidentally opened it with notepad making it a notepad and now i need help undoing it. i dont know how to undo it and i need help because of it

edit: and when i tryed to reinstall it. it made it so every time i try to install it. it becomes a notepad and i dont know how to make it to stop (and sorry for not adressing it the first time)

editedit: i used WinRAR and file explorer and have Ryu mod manager just so you know

**Comment by ibldzn** [comment]
you're not supposed to launch the mod manually, the game will automatically load it for you.
anyway
https://www.partitionwizard.com/partitionmanager/remove-file-association-windows-10.html
you need to remove the `.asi` key

**Comment by LioTheBadAss** [comment]
> you're not supposed to launch the mod manually, the game will automatically load it for you.
> 
> anyway check out this article, https://www.partitionwizard.com/partitionmanager/remove-file-association-windows-10.html you need to remove the `.asi` key

the entire .asi file or something specific in the file?

**Comment by ibldzn** [comment]
![img](https://www.partitionwizard.com/images/uploads/articles/2020/07/remove-file-association-windows-10/remove-file-association-windows-10-1.png)

find the `.asi` then delete the thing

**Comment by LioTheBadAss** [comment]
> ![img](https://camo.githubusercontent.com/6e914d8b973055a4c8435e790e0f2ff27554c3b1992517b191908a4f1bd808f0/68747470733a2f2f7777772e706172746974696f6e77697a6172642e636f6d2f696d616765732f75706c6f6164732f61727469636c65732f323032302f30372f72656d6f76652d66696c652d6173736f63696174696f6e2d77696e646f77732d31302f72656d6f76652d66696c652d6173736f63696174696f6e2d77696e646f77732d31302d312e706e67)
> 
> find the `.asi` then delete the thing

ok and thanks my dude

**Comment by LioTheBadAss** [comment]
> you're not supposed to launch the mod manually, the game will automatically load it for you.
> 
> anyway check out this article, https://www.partitionwizard.com/partitionmanager/remove-file-association-windows-10.html you need to remove the `.asi` key

btw what do you mean by "do it automaticly?"
