### ISSUE TITLE
help with the 4bind.asi error

### ISSUE THREAD

**Issue by johnyakuza** [ibldzn/yakuza-0-legend-style-fix#19]
![image](https://user-images.githubusercontent.com/123521870/214456213-4ce66480-c528-4de9-a4f3-87ddaf58570f.png)
so basically it happens this when i open the game, i really don't know what's causing this, and apparently my friend got this error too, so yeah

**Comment by ibldzn** [comment]
have you tried using the dxgi.dll file?

**Comment by johnyakuza** [comment]
> have you tried using the dxgi.dll file?

yeah, it works. but i want the keybind to be on 4 to change the legend
but when i put only that file which is the Y0LSF_4BIND, it gives me that error

**Comment by ibldzn** [comment]
ah, so you wanted to change the keybinding?  I'll update the mod once I get home in a few hours so you can use a custom keybinding

**Comment by johnyakuza** [comment]
yep, that's what i want, if possible

**Comment by ibldzn** [comment]
hey, can you help me to test this? I don't have the game installed at the moment, downloading it would take too much time.

1. Extract [Y0LSF with custom keybind.zip](https://github.com/ibldzn/yakuza-0-legend-style-fix/files/10499716/Y0LSF.with.custom.keybind.zip) then put both file inside your game directory
2. Check and report back to me

also, don't forget to delete your old `.asi` file

**Comment by johnyakuza** [comment]
it worked without any issues, thank you so much my man <3

**Comment by ibldzn** [comment]
glad it worked! also, thank you for testing it for me, I'll push the update now 😃
