### ISSUE TITLE
Throws up an error on launching the game.

### ISSUE THREAD

**Issue by FuckJauneArc** [ibldzn/yakuza-0-legend-style-fix#3]
When launching with the mod, it throws up an error that reads:

> proxy::init - failed to get address for create dxgifactory2!

The game still runs, but the mod doesn't function.

**Comment by ibldzn** [comment]
please elaborate more about 

> the mod doesn't function.

it still works fine. https://streamable.com/csra0t

try this
[dxgi.zip](https://github.com/ibldzn/yakuza-0-legend-style-fix/files/5916016/dxgi.zip)
 I've added windows version check. will push the update later

**Comment by ibldzn** [comment]
should be fixed in latest release, I'm waiting for your update

**Comment by FuckJauneArc** [comment]
Yeah it's 100% fixed now. Thanks for your patience! I'm gonna go plaster this mod everywhere online.

**Comment by ibldzn** [comment]
no problem, glad I'm able to solve the problem. and thanks :D
